### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Bronz0** [stevej2608/dash-holoniq-wordcloud#1]
Hi there,

I ran through this issue when I tried to execute my code:
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'D:\\workspace\\dash_wordcloud\\venv\\lib\\site-packages\\dash_holoniq_wordcloud\\dash_holoniq_wordcloud.dev.js'

I installed the package using: `pip install dash-holoniq-wordcloud`

**Comment by stevej2608** [comment]
Hi, Thanks for flagging the problem. 

The example code in usage.py calls serve_app() in app.py. In  serve_app(), line 30, remove *dev_tools_serve_dev_bundles=True*. The demo should now run OK.

I need to put the following changes through:

* include the dev bundles with the package
* remove *dev_tools_serve_dev_bundles=True* in the demo.

I'll do that tomorrow if I have the time.

Cheers, Steve.

**Comment by stevej2608** [comment]
Package version 0.0.4 in on pypi. Cheers.

**Comment by Bronz0** [comment]
It's working, thank you man.
